
const lang = {
    en: {
        lang: "Language",
        titlename: "HungBok",
        info: "Information",
        korean_name: "Korean Name",
        sex: "Gender",
        sex_answer: "Man",
        birth: "Year of Birth",
        birth_answer: "2003",
        birthday: "Date of Birth",
        birthday_answer: "June 24, 2003",
        english_name: "English Name",
        country: "Nationality",
        country_answer: "Republic of Korea",
        live: "Residence",
        live_answer: "Incheon",
        favorite_lang: "Favorite Language",
        japanese_name: "Japanese Name",
        blood: "Blood Type",
        hobby: "Hobby",
        hobby_answer: "to collect",
        like: "Like",
        like_answer: "Game, Anime",
        chinese_name: "Chinese Name",
        color: "Favorite Color",
        mbti: "MBTI",
        dislike: "Dislike",
        dislike_answer: "Insect",
        email: "E-mail",
        social_account: "Social Accounts",
        game_account: "Game Accounts",
        copy: "Copy",
        move: "Link",
        copytoclip: "Copy to Clipboard",
        copied: "Copied.",
        guideline: "*In the event of any malicious acts or attempts, including acts that violate the terms of service, such as excessive friend requests without clear reasons or inducing difficulties in using an account, each government agency or You can proceed with the investigation by requesting a similar organization.",
        favorite_game: "Favorite Games",
        favorite_movie: "Favorite Movies",
        favorite_anime: "Favorite Animations",
        favorite_drama: "Favorite TV Series",
        grand_theft_auto_5: "Grand Theft Auto V",
        cyberpunk_2077: "Cyberpunk 2077",
        fortnite: "Fortnite",
        detroit_become_human: "Detroit: Become Human",
        inside: "INSIDE",
        biohazard_7_resident_evil: "Resident Evil 7 Biohazard",
        portal_2: "Portal 2",
        minecraft: "Minecraft",
        the_last_of_us_remastered: "The Last of Us Remastered",
        super_mario_maker_2: "Super Mario Maker 2",
        pokemon_heartgold: "Pokémon HeartGold",
        tenki_no_ko: "Weathering With You",
        parasite: "Parasite",
        kimetsu_no_yaiba_movie_mugen_ressha_hen: "Demon Slayer -Kimetsu no Yaiba- the Movie: Mugen Train Arc",
        kimi_no_suizou_o_tabetai: "I Want to Eat Your Pancreas",
        the_avengers: "The Avengers",
        sen_to_chihiro_no_kamikakushi: "Spirited Away",
        kimi_no_na_wa: "Your Name.",
        gravity: "Gravity",
        frozen_2: "Frozen II",
        the_island: "The Island",
        in_time: "In Time",
        meitantei_conan: "Case Closed",
        kimetsu_no_yaiba: "Demon Slayer: Kimetsu no Yaiba",
        the_idolmaster: "THE iDOLM@STER",
        kakegurui: "Kakegurui",
        crayon_shin_chan: "Crayon Shin-chan",
        spy_x_family: "SPY × FAMILY",
        karakai_jouzu_no_takagi_san: "Teasing Master Takagi-san",
        doraemon: "Doraemon",
        squid_game: "SQUID GAME",
        la_casa_de_papel: "La Casa de Papel",
        strangers_from_hell: "Strangers from Hell",
        la_casa_de_papel_corea: "Money Heist: Korea - Joint Economic Area",
        the_uncanny_counter: "The Uncanny Counter",
        oh_my_ghost: "Oh My Ghost",
        kono_subarashii_sekai_ni_shukufuku_o: "Konosuba: God's Blessing on This Wonderful World!",
        senpai_ga_uzai_kouhai_no_hanashi: "My Senpai is Annoying",
        boku_dake_ga_inai_machi: "Erased",
        yaku_neba: "The Promised Neverland",
        violet_evergarden: "Violet Evergarden",
        the_silent_sea: "The Silent Sea",
        violet_evergarden_movie: "Violet Evergarden: The Movie",
        love_death_plus_robots: "LOVE DEATH + ROBOTS",
        black_mirror: "Black Mirror",
        busted: "Busted!",
        watch_history: "Watch History",
        cyberpunk_edgerunners: "Cyberpunk: Edgerunners",
        psycho_pass: "PSYCHO-PASS",
        summer_time_render: "Summer Time Rendering",
        aiuta: "Sing a Bit of Harmony",
        game_platform_account: "Game Platform Accounts",
        donation_account: "Donation Accounts",
        height: "Height",
        height_answer: "5'6''",
        weight: "Weight",
        weight_answer: "132lb",
        stray: "Stray",
        journey: "Journey",
        biohazard_2: "Resident Evil 2",
        half_life: "Half-Life",
        animal_crossing_new_horizons: "Animal Crossing: New Horizons",
        the_legend_of_zelda_breath_of_the_wild: "The Legend of Zelda: Breath of the Wild",
        biohazard_village: "Resident Evil Village",
        little_nightmares: "Little Nightmares",
        vrchat: "VRChat",
        overwatch: "Overwatch",
        favorite_anime_the_movie: "Favorite Animation The Movies",
        community_account: "Community Accounts",
    },
    de: {
        lang: "Sprache",
        titlename: "HungBok",
        info: "Information",
        korean_name: "Koreanischer Name",
        sex: "Geschlecht",
        sex_answer: "Mann",
        birth: "Geburtsjahr",
        birth_answer: "2003",
        birthday: "Geburtsdatum",
        birthday_answer: "24. Juni 2003",
        english_name: "Englischer Name",
        country: "Nationalität",
        country_answer: "Republik Korea",
        live: "Residenz",
        live_answer: "Incheon",
        favorite_lang: "Lieblingssprache",
        japanese_name: "Japanischer Name",
        blood: "Blutgruppe",
        hobby: "Hobby",
        hobby_answer: "sammeln",
        like: "Gefällt mir",
        like_answer: "Spiel, Animation",
        chinese_name: "Chinesischer Name",
        color: "Lieblingsfarbe",
        mbti: "MBTI",
        dislike: "Abneigung",
        dislike_answer: "Insekt",
        email: "Email",
        social_account: "Soziale Konten",
        game_account: "Spielkonten",
        copy: "Kopieren",
        move: "Link",
        copytoclip: "In die Zwischenablage kopieren",
        copied: "Kopiert.",
        guideline: "*Im Falle böswilliger Handlungen oder Versuche, einschließlich Handlungen, die gegen die Nutzungsbedingungen verstoßen, wie z. B. übermäßige Freundschaftsanfragen ohne klare Gründe oder das Hervorrufen von Schwierigkeiten bei der Verwendung eines Kontos, kann jede Regierungsbehörde oder Sie die Untersuchung fortsetzen, indem Sie eine ähnliche Organisation anfordern.",
        favorite_game: "Lieblingsspiele",
        favorite_movie: "Lieblingsfilme",
        favorite_anime: "Lieblingsanimationen",
        favorite_drama: "Lieblings TV-Serie",
        grand_theft_auto_5: "Grand Theft Auto V",
        cyberpunk_2077: "Cyberpunk 2077",
        fortnite: "Fortnite",
        detroit_become_human: "Detroit: Become Human",
        inside: "INSIDE",
        biohazard_7_resident_evil: "Resident Evil 7 Biohazard",
        portal_2: "Portal 2",
        minecraft: "Minecraft",
        the_last_of_us_remastered: "The Last of Us Remastered",
        super_mario_maker_2: "Super Mario Maker 2",
        pokemon_heartgold: "Pokémon HeartGold",
        tenki_no_ko: "Weathering With You",
        parasite: "Parasite",
        kimetsu_no_yaiba_movie_mugen_ressha_hen: "Demon Slayer -Kimetsu no Yaiba- the Movie: Mugen Train Arc",
        kimi_no_suizou_o_tabetai: "I Want to Eat Your Pancreas",
        the_avengers: "The Avengers",
        sen_to_chihiro_no_kamikakushi: "Spirited Away",
        kimi_no_na_wa: "Your Name.",
        gravity: "Gravity",
        frozen_2: "Frozen II",
        the_island: "The Island",
        in_time: "In Time",
        meitantei_conan: "Detective Conan",
        kimetsu_no_yaiba: "Demon Slayer: Kimetsu no Yaiba",
        the_idolmaster: "THE iDOLM@STER",
        kakegurui: "Kakegurui",
        crayon_shin_chan: "Crayon Shin-chan",
        spy_x_family: "SPY × FAMILY",
        karakai_jouzu_no_takagi_san: "Teasing Master Takagi-san",
        doraemon: "Doraemon",
        squid_game: "SQUID GAME",
        la_casa_de_papel: "La Casa de Papel",
        strangers_from_hell: "Strangers from Hell",
        la_casa_de_papel_corea: "Money Heist: Korea - Joint Economic Area",
        the_uncanny_counter: "The Uncanny Counter",
        oh_my_ghost: "Oh My Ghost",
        kono_subarashii_sekai_ni_shukufuku_o: "Konosuba: God's Blessing on This Wonderful World!",
        senpai_ga_uzai_kouhai_no_hanashi: "My Senpai is Annoying",
        boku_dake_ga_inai_machi: "Erased",
        yaku_neba: "The Promised Neverland",
        violet_evergarden: "Violet Evergarden",
        the_silent_sea: "The Silent Sea",
        violet_evergarden_movie: "Violet Evergarden: The Movie",
        love_death_plus_robots: "LOVE DEATH + ROBOTS",
        black_mirror: "Black Mirror",
        busted: "Busted!",
        watch_history: "Geschichte ansehen",
        cyberpunk_edgerunners: "Cyberpunk: Edgerunners",
        psycho_pass: "PSYCHO-PASS",
        summer_time_render: "Summer Time Rendering",
        aiuta: "Sing a Bit of Harmony",
        game_platform_account: "Spielplattformkonten",
        donation_account: "Spendenkonten",
        height: "Höhe",
        height_answer: "170cm",
        weight: "Gewicht",
        weight_answer: "60kg",
        stray: "Stray",
        journey: "Journey",
        biohazard_2: "Resident Evil 2",
        half_life: "Half-Life",
        animal_crossing_new_horizons: "Animal Crossing: New Horizons",
        the_legend_of_zelda_breath_of_the_wild: "The Legend of Zelda: Breath of the Wild",
        biohazard_village: "Resident Evil Village",
        little_nightmares: "Little Nightmares",
        vrchat: "VRChat",
        overwatch: "Overwatch",
        favorite_anime_the_movie: "Lieblingsanimation Der Film",
        community_account: "Gemeinschaftskonten",
    },
    es: {
        lang: "Idioma",
        titlename: "HungBok",
        info: "Información",
        korean_name: "Nombre coreano",
        sex: "Género",
        sex_answer: "Hombre",
        birth: "Año de nacimiento",
        birth_answer: "2003",
        birthday: "Fecha de nacimiento",
        birthday_answer: "24 de junio de 2003",
        english_name: "Nombre en inglés",
        country: "Nacionalidad",
        country_answer: "República de Corea",
        live: "Residencia",
        live_answer: "Incheon",
        favorite_lang: "Idioma favorito",
        japanese_name: "Nombre japonés",
        blood: "Tipo de sangre",
        hobby: "Afición",
        hobby_answer: "coleccionar",
        like: "Me gusta",
        like_answer: "Juego, Animación",
        chinese_name: "Nombre chino",
        color: "Color favorito",
        mbti: "MBTI",
        dislike: "No me gusta",
        dislike_answer: "Insecto",
        email: "Email",
        social_account: "Cuentas Sociales",
        game_account: "Cuentas de juego",
        copy: "Copiar",
        move: "Enlace",
        copytoclip: "Copiar al portapapeles",
        copied: "Copiado.",
        guideline: "*En el caso de actos o intentos maliciosos, incluidos actos que violen los términos del servicio, como solicitudes de amistad excesivas sin razones claras o que induzcan dificultades para usar una cuenta, cada agencia gubernamental o Usted puede continuar con la investigación solicitando una organización similar.",
        favorite_game: "Juegos favoritos",
        favorite_movie: "Peliculas favoritas",
        favorite_anime: "Animaciones favoritas",
        favorite_drama: "Serie de televisión favorita",
        grand_theft_auto_5: "Grand Theft Auto V",
        cyberpunk_2077: "Cyberpunk 2077",
        fortnite: "Fortnite",
        detroit_become_human: "Detroit: Become Human",
        inside: "INSIDE",
        biohazard_7_resident_evil: "Resident Evil 7 Biohazard",
        portal_2: "Portal 2",
        minecraft: "Minecraft",
        the_last_of_us_remastered: "The Last of Us Remastered",
        super_mario_maker_2: "Super Mario Maker 2",
        pokemon_heartgold: "Pokémon HeartGold",
        tenki_no_ko: "Weathering With You",
        parasite: "Parasite",
        kimetsu_no_yaiba_movie_mugen_ressha_hen: "Demon Slayer -Kimetsu no Yaiba- the Movie: Mugen Train Arc",
        kimi_no_suizou_o_tabetai: "I Want to Eat Your Pancreas",
        the_avengers: "The Avengers",
        sen_to_chihiro_no_kamikakushi: "Spirited Away",
        kimi_no_na_wa: "Your Name.",
        gravity: "Gravity",
        frozen_2: "Frozen II",
        the_island: "The Island",
        in_time: "In Time",
        meitantei_conan: "Detective Conan",
        kimetsu_no_yaiba: "Demon Slayer: Kimetsu no Yaiba",
        the_idolmaster: "THE iDOLM@STER",
        kakegurui: "Kakegurui",
        crayon_shin_chan: "Crayon Shin-chan",
        spy_x_family: "SPY × FAMILY",
        karakai_jouzu_no_takagi_san: "Teasing Master Takagi-san",
        doraemon: "Doraemon",
        squid_game: "SQUID GAME",
        la_casa_de_papel: "La Casa de Papel",
        strangers_from_hell: "Strangers from Hell",
        la_casa_de_papel_corea: "Money Heist: Korea - Joint Economic Area",
        the_uncanny_counter: "The Uncanny Counter",
        oh_my_ghost: "Oh My Ghost",
        kono_subarashii_sekai_ni_shukufuku_o: "Konosuba: God's Blessing on This Wonderful World!",
        senpai_ga_uzai_kouhai_no_hanashi: "My Senpai is Annoying",
        boku_dake_ga_inai_machi: "Erased",
        yaku_neba: "The Promised Neverland",
        violet_evergarden: "Violet Evergarden",
        the_silent_sea: "The Silent Sea",
        violet_evergarden_movie: "Violet Evergarden: The Movie",
        love_death_plus_robots: "LOVE DEATH + ROBOTS",
        black_mirror: "Black Mirror",
        busted: "Busted!",
        watch_history: "Ver historial",
        cyberpunk_edgerunners: "Cyberpunk: Edgerunners",
        psycho_pass: "PSYCHO-PASS",
        summer_time_render: "Summer Time Rendering",
        aiuta: "Sing a Bit of Harmony",
        game_platform_account: "Cuentas de plataforma de juego",
        donation_account: "Cuentas de donación",
        height: "altura",
        height_answer: "170cm",
        weight: "peso",
        weight_answer: "60kg",
        stray: "Stray",
        journey: "Journey",
        biohazard_2: "Resident Evil 2",
        half_life: "Half-Life",
        animal_crossing_new_horizons: "Animal Crossing: New Horizons",
        the_legend_of_zelda_breath_of_the_wild: "The Legend of Zelda: Breath of the Wild",
        biohazard_village: "Resident Evil Village",
        little_nightmares: "Little Nightmares",
        vrchat: "VRChat",
        overwatch: "Overwatch",
        favorite_anime_the_movie: "Animación Favorita La Película",
        community_account: "Cuentas comunitarias",
    },
    fr: {
        lang: "Langue",
        titlename: "HungBok",
        info: "Informations",
        korean_name: "Nom coréen",
        sex: "Sexe",
        sex_answer: "Homme",
        birth: "Année de naissance",
        birth_answer: "2003",
        birthday: "Date de naissance",
        birthday_answer: "24 juin 2003",
        english_name: "Nom anglais",
        country: "Nationalité",
        country_answer: "République de Corée",
        live: "Résidence",
        live_answer: "Incheon",
        favorite_lang: "Langue préférée",
        japanese_name: "Nom japonais",
        blood: "Groupe sanguin",
        hobby: "passe-temps",
        hobby_answer: "à collectionner",
        like: "J'aime",
        like_answer: "Jeu, Animation",
        chinese_name: "Nom chinois",
        color: "Couleur préférée",
        mbti: "MBTI",
        dislike: "Je n'aime pas",
        dislike_answer: "Insecte",
        email: "E-mail",
        social_account: "Comptes sociaux",
        game_account: "Comptes de jeu",
        copy: "Copier",
        move: "Lien",
        copytoclip: "Copier dans le presse-papiers",
        copied: "Copié.",
        guideline: "*En cas d'actes ou de tentatives malveillants, y compris des actes qui violent les conditions d'utilisation, tels que des demandes d'amis excessives sans raisons claires ou induisant des difficultés à utiliser un compte, chaque agence gouvernementale ou Vous pouvez poursuivre l'enquête en demandant à une organisation similaire.",
        favorite_game: "Jeux favoris",
        favorite_movie: "Films préférés",
        favorite_anime: "Animations préférées",
        favorite_drama: "Série télévisée préférée",
        grand_theft_auto_5: "Grand Theft Auto V",
        cyberpunk_2077: "Cyberpunk 2077",
        fortnite: "Fortnite",
        detroit_become_human: "Detroit: Become Human",
        inside: "INSIDE",
        biohazard_7_resident_evil: "Resident Evil 7 Biohazard",
        portal_2: "Portal 2",
        minecraft: "Minecraft",
        the_last_of_us_remastered: "The Last of Us Remastered",
        super_mario_maker_2: "Super Mario Maker 2",
        pokemon_heartgold: "Pokémon HeartGold",
        tenki_no_ko: "Weathering With You",
        parasite: "Parasite",
        kimetsu_no_yaiba_movie_mugen_ressha_hen: "Demon Slayer -Kimetsu no Yaiba- the Movie: Mugen Train Arc",
        kimi_no_suizou_o_tabetai: "I Want to Eat Your Pancreas",
        the_avengers: "The Avengers",
        sen_to_chihiro_no_kamikakushi: "Spirited Away",
        kimi_no_na_wa: "Your Name.",
        gravity: "Gravity",
        frozen_2: "Frozen II",
        the_island: "The Island",
        in_time: "In Time",
        meitantei_conan: "Detective Conan",
        kimetsu_no_yaiba: "Demon Slayer: Kimetsu no Yaiba",
        the_idolmaster: "THE iDOLM@STER",
        kakegurui: "Kakegurui",
        crayon_shin_chan: "Crayon Shin-chan",
        spy_x_family: "SPY × FAMILY",
        karakai_jouzu_no_takagi_san: "Teasing Master Takagi-san",
        doraemon: "Doraemon",
        squid_game: "SQUID GAME",
        la_casa_de_papel: "La Casa de Papel",
        strangers_from_hell: "Strangers from Hell",
        la_casa_de_papel_corea: "Money Heist: Korea - Joint Economic Area",
        the_uncanny_counter: "The Uncanny Counter",
        oh_my_ghost: "Oh My Ghost",
        kono_subarashii_sekai_ni_shukufuku_o: "Konosuba: God's Blessing on This Wonderful World!",
        senpai_ga_uzai_kouhai_no_hanashi: "My Senpai is Annoying",
        boku_dake_ga_inai_machi: "Erased",
        yaku_neba: "The Promised Neverland",
        violet_evergarden: "Violet Evergarden",
        the_silent_sea: "The Silent Sea",
        violet_evergarden_movie: "Violet Evergarden: The Movie",
        love_death_plus_robots: "LOVE DEATH + ROBOTS",
        black_mirror: "Black Mirror",
        busted: "Busted!",
        watch_history: "Historique des visionnages",
        cyberpunk_edgerunners: "Cyberpunk: Edgerunners",
        psycho_pass: "PSYCHO-PASS",
        summer_time_render: "Summer Time Rendering",
        aiuta: "Sing a Bit of Harmony",
        game_platform_account: "Comptes de plate-forme de jeu",
        donation_account: "Comptes de dons",
        height: "hauteur",
        height_answer: "170cm",
        weight: "lester",
        weight_answer: "60kg",
        stray: "Stray",
        journey: "Journey",
        biohazard_2: "Resident Evil 2",
        half_life: "Half-Life",
        animal_crossing_new_horizons: "Animal Crossing: New Horizons",
        the_legend_of_zelda_breath_of_the_wild: "The Legend of Zelda: Breath of the Wild",
        biohazard_village: "Resident Evil Village",
        little_nightmares: "Little Nightmares",
        vrchat: "VRChat",
        overwatch: "Overwatch",
        favorite_anime_the_movie: "Animation préférée Le film",
        community_account: "Comptes communautaires",
    },
    it: {
        lang: "Lingua",
        titlename: "HungBok",
        info: "Informazione",
        korean_name: "Nome coreano",
        sex: "Sesso",
        sex_answer: "Uomo",
        birth: "Anno di nascita",
        birth_answer: "2003",
        birthday: "Data di nascita",
        birthday_answer: "24 giugno 2003",
        english_name: "Nome inglese",
        country: "Nazionalità",
        country_answer: "Repubblica di Corea",
        live: "Residence",
        live_answer: "Incheon",
        favorite_lang: "Lingua preferita",
        japanese_name: "Nome giapponese",
        blood: "gruppo sanguigno",
        hobby: "Hobby",
        hobby_answer: "collezionare",
        like: "Mi piace",
        like_answer: "Gioco, animazione",
        chinese_name: "Nome cinese",
        color: "Colore preferito",
        mbti: "MBTI",
        dislike: "Non mi piace",
        dislike_answer: "Insetto",
        email: "E-mail",
        social_account: "Account Social",
        game_account: "Account di gioco",
        copy: "Copia",
        move: "Link",
        copytoclip: "Copia negli appunti",
        copied: "Copiato.",
        guideline: "*In caso di atti o tentativi dannosi, inclusi atti che violano i termini del servizio, come richieste di amicizia eccessive senza motivi chiari o che inducano difficoltà nell'utilizzo di un account, ciascuna agenzia governativa o l'Utente può procedere con l'indagine richiedendo a un'organizzazione simile.",
        favorite_game: "Giochi preferiti",
        favorite_movie: "Film preferiti",
        favorite_anime: "Animazioni preferite",
        favorite_drama: "Serie TV preferita",
        grand_theft_auto_5: "Grand Theft Auto V",
        cyberpunk_2077: "Cyberpunk 2077",
        fortnite: "Fortnite",
        detroit_become_human: "Detroit: Become Human",
        inside: "INSIDE",
        biohazard_7_resident_evil: "Resident Evil 7 Biohazard",
        portal_2: "Portal 2",
        minecraft: "Minecraft",
        the_last_of_us_remastered: "The Last of Us Remastered",
        super_mario_maker_2: "Super Mario Maker 2",
        pokemon_heartgold: "Pokémon HeartGold",
        tenki_no_ko: "Weathering With You",
        parasite: "Parasite",
        kimetsu_no_yaiba_movie_mugen_ressha_hen: "Demon Slayer -Kimetsu no Yaiba- the Movie: Mugen Train Arc",
        kimi_no_suizou_o_tabetai: "I Want to Eat Your Pancreas",
        the_avengers: "The Avengers",
        sen_to_chihiro_no_kamikakushi: "Spirited Away",
        kimi_no_na_wa: "Your Name.",
        gravity: "Gravity",
        frozen_2: "Frozen II",
        the_island: "The Island",
        in_time: "In Time",
        meitantei_conan: "Detective Conan",
        kimetsu_no_yaiba: "Demon Slayer: Kimetsu no Yaiba",
        the_idolmaster: "THE iDOLM@STER",
        kakegurui: "Kakegurui",
        crayon_shin_chan: "Crayon Shin-chan",
        spy_x_family: "SPY × FAMILY",
        karakai_jouzu_no_takagi_san: "Teasing Master Takagi-san",
        doraemon: "Doraemon",
        squid_game: "SQUID GAME",
        la_casa_de_papel: "La Casa de Papel",
        strangers_from_hell: "Strangers from Hell",
        la_casa_de_papel_corea: "Money Heist: Korea - Joint Economic Area",
        the_uncanny_counter: "The Uncanny Counter",
        oh_my_ghost: "Oh My Ghost",
        kono_subarashii_sekai_ni_shukufuku_o: "Konosuba: God's Blessing on This Wonderful World!",
        senpai_ga_uzai_kouhai_no_hanashi: "My Senpai is Annoying",
        boku_dake_ga_inai_machi: "Erased",
        yaku_neba: "The Promised Neverland",
        violet_evergarden: "Violet Evergarden",
        the_silent_sea: "The Silent Sea",
        violet_evergarden_movie: "Violet Evergarden: The Movie",
        love_death_plus_robots: "LOVE DEATH + ROBOTS",
        black_mirror: "Black Mirror",
        busted: "Busted!",
        watch_history: "Guarda Storia",
        cyberpunk_edgerunners: "Cyberpunk: Edgerunners",
        psycho_pass: "PSYCHO-PASS",
        summer_time_render: "Summer Time Rendering",
        aiuta: "Sing a Bit of Harmony",
        game_platform_account: "Account della piattaforma di gioco",
        donation_account: "Conti di donazione",
        height: "altezza",
        height_answer: "170cm",
        weight: "peso",
        weight_answer: "60kg",
        stray: "Stray",
        journey: "Journey",
        biohazard_2: "Resident Evil 2",
        half_life: "Half-Life",
        animal_crossing_new_horizons: "Animal Crossing: New Horizons",
        the_legend_of_zelda_breath_of_the_wild: "The Legend of Zelda: Breath of the Wild",
        biohazard_village: "Resident Evil Village",
        little_nightmares: "Little Nightmares",
        vrchat: "VRChat",
        overwatch: "Overwatch",
        favorite_anime_the_movie: "Animazione preferita Il film",
        community_account: "Conti della comunità",
    },
    pt: {
        lang: "Linguagem",
        titlename: "HungBok",
        info: "Em formação",
        korean_name: "Nome Coreano",
        sex: "Gênero",
        sex_answer: "Homem",
        birth: "Ano de nascimento",
        birth_answer: "2003",
        birthday: "Data de nascimento",
        birthday_answer: "24 de junho de 2003",
        english_name: "Nome em inglês",
        country: "Nacionalidade",
        country_answer: "República da Coreia",
        live: "Residência",
        live_answer: "Incheon",
        favorite_lang: "Idioma Favorito",
        japanese_name: "Nome Japonês",
        blood: "Tipo sanguíneo",
        hobby: "Passatempo",
        hobby_answer: "colecionar",
        like: "Curtir",
        like_answer: "Jogo, Animação",
        chinese_name: "Nome Chinês",
        color: "Cor Favorita",
        mbti: "MBTI",
        dislike: "Não gosto",
        dislike_answer: "Inseto",
        email: "E-mail",
        social_account: "Contas Sociais",
        game_account: "Contas do jogo",
        copy: "Copiar",
        move: "Link",
        copytoclip: "Copiar para a área de transferência",
        copied: "Copiado.",
        guideline: "*No caso de quaisquer atos ou tentativas maliciosas, incluindo atos que violem os termos de serviço, como solicitações excessivas de amizade sem motivos claros ou induzindo dificuldades no uso de uma conta, cada agência governamental ou Você pode prosseguir com a investigação solicitando uma organização semelhante.",
        favorite_game: "Jogos favoritos",
        favorite_movie: "Filmes favoritos",
        favorite_anime: "Animações favoritas",
        favorite_drama: "Série de TV favorita",
        grand_theft_auto_5: "Grand Theft Auto V",
        cyberpunk_2077: "Cyberpunk 2077",
        fortnite: "Fortnite",
        detroit_become_human: "Detroit: Become Human",
        inside: "INSIDE",
        biohazard_7_resident_evil: "Resident Evil 7 Biohazard",
        portal_2: "Portal 2",
        minecraft: "Minecraft",
        the_last_of_us_remastered: "The Last of Us Remastered",
        super_mario_maker_2: "Super Mario Maker 2",
        pokemon_heartgold: "Pokémon HeartGold",
        tenki_no_ko: "Weathering With You",
        parasite: "Parasite",
        kimetsu_no_yaiba_movie_mugen_ressha_hen: "Demon Slayer -Kimetsu no Yaiba- the Movie: Mugen Train Arc",
        kimi_no_suizou_o_tabetai: "I Want to Eat Your Pancreas",
        the_avengers: "The Avengers",
        sen_to_chihiro_no_kamikakushi: "Spirited Away",
        kimi_no_na_wa: "Your Name.",
        gravity: "Gravity",
        frozen_2: "Frozen II",
        the_island: "The Island",
        in_time: "In Time",
        meitantei_conan: "Detective Conan",
        kimetsu_no_yaiba: "Demon Slayer: Kimetsu no Yaiba",
        the_idolmaster: "THE iDOLM@STER",
        kakegurui: "Kakegurui",
        crayon_shin_chan: "Crayon Shin-chan",
        spy_x_family: "SPY × FAMILY",
        karakai_jouzu_no_takagi_san: "Teasing Master Takagi-san",
        doraemon: "Doraemon",
        squid_game: "SQUID GAME",
        la_casa_de_papel: "La Casa de Papel",
        strangers_from_hell: "Strangers from Hell",
        la_casa_de_papel_corea: "Money Heist: Korea - Joint Economic Area",
        the_uncanny_counter: "The Uncanny Counter",
        oh_my_ghost: "Oh My Ghost",
        kono_subarashii_sekai_ni_shukufuku_o: "Konosuba: God's Blessing on This Wonderful World!",
        senpai_ga_uzai_kouhai_no_hanashi: "My Senpai is Annoying",
        boku_dake_ga_inai_machi: "Erased",
        yaku_neba: "The Promised Neverland",
        violet_evergarden: "Violet Evergarden",
        the_silent_sea: "The Silent Sea",
        violet_evergarden_movie: "Violet Evergarden: The Movie",
        love_death_plus_robots: "LOVE DEATH + ROBOTS",
        black_mirror: "Black Mirror",
        busted: "Busted!",
        watch_history: "Histórico de exibição",
        cyberpunk_edgerunners: "Cyberpunk: Edgerunners",
        psycho_pass: "PSYCHO-PASS",
        summer_time_render: "Summer Time Rendering",
        aiuta: "Sing a Bit of Harmony",
        game_platform_account: "Contas de plataforma de jogo",
        donation_account: "Contas de doação",
        height: "altura",
        height_answer: "170cm",
        weight: "peso",
        weight_answer: "60kg",
        stray: "Stray",
        journey: "Journey",
        biohazard_2: "Resident Evil 2",
        half_life: "Half-Life",
        animal_crossing_new_horizons: "Animal Crossing: New Horizons",
        the_legend_of_zelda_breath_of_the_wild: "The Legend of Zelda: Breath of the Wild",
        biohazard_village: "Resident Evil Village",
        little_nightmares: "Little Nightmares",
        vrchat: "VRChat",
        overwatch: "Overwatch",
        favorite_anime_the_movie: "Animação Favorita O Filme",
        community_account: "Contas da comunidade",
    },
    ru: {
        lang: "Язык",
        titlename: "Хунгбок",
        info: "Информация",
        korean_name: "Корейское имя",
        sex: "Пол",
        sex_answer: "Мужчина",
        birth: "Год рождения",
        birth_answer: "2003",
        birthday: "Дата рождения",
        birthday_answer: "24 июня 2003 г.",
        english_name: "Английское имя",
        country: "Национальность",
        country_answer: "Республика Корея",
        live: "Резиденция",
        live_answer: "Инчхон",
        favorite_lang: "Любимый язык",
        japanese_name: "Японское имя",
        blood: "Группа крови",
        hobby: "Хобби",
        hobby_answer: "собирать",
        like: "Нравится",
        like_answer: "Игра, Анимация",
        chinese_name: "Китайское имя",
        color: "Любимый цвет",
        mbti: "МБТИ",
        dislike: "Не нравится",
        dislike_answer: "Насекомое",
        email: "Эл. адрес",
        social_account: "Социальные аккаунты",
        game_account: "Игровые аккаунты",
        copy: "Копировать",
        move: "Ссылка",
        copytoclip: "Копировать в буфер обмена",
        copied: "Скопировано.",
        guideline: "*В случае любых злонамеренных действий или попыток, в том числе действий, нарушающих условия предоставления услуг, таких как чрезмерные запросы на добавление в друзья без явных причин или вызывающие трудности в использовании учетной записи, каждое государственное учреждение или Вы можете продолжить расследование, обратившись в аналогичную организацию.",
        favorite_game: "Любимые игры",
        favorite_movie: "Любимые фильмы",
        favorite_anime: "Любимые анимации",
        favorite_drama: "Любимый сериал",
        grand_theft_auto_5: "Grand Theft Auto V",
        cyberpunk_2077: "Cyberpunk 2077",
        fortnite: "Fortnite",
        detroit_become_human: "Detroit: Become Human",
        inside: "INSIDE",
        biohazard_7_resident_evil: "Resident Evil 7 Biohazard",
        portal_2: "Portal 2",
        minecraft: "Minecraft",
        the_last_of_us_remastered: "The Last of Us Remastered",
        super_mario_maker_2: "Super Mario Maker 2",
        pokemon_heartgold: "Pokémon HeartGold",
        tenki_no_ko: "Weathering With You",
        parasite: "Parasite",
        kimetsu_no_yaiba_movie_mugen_ressha_hen: "Demon Slayer -Kimetsu no Yaiba- the Movie: Mugen Train Arc",
        kimi_no_suizou_o_tabetai: "I Want to Eat Your Pancreas",
        the_avengers: "The Avengers",
        sen_to_chihiro_no_kamikakushi: "Spirited Away",
        kimi_no_na_wa: "Your Name.",
        gravity: "Gravity",
        frozen_2: "Frozen II",
        the_island: "The Island",
        in_time: "In Time",
        meitantei_conan: "Detective Conan",
        kimetsu_no_yaiba: "Demon Slayer: Kimetsu no Yaiba",
        the_idolmaster: "THE iDOLM@STER",
        kakegurui: "Kakegurui",
        crayon_shin_chan: "Crayon Shin-chan",
        spy_x_family: "SPY × FAMILY",
        karakai_jouzu_no_takagi_san: "Teasing Master Takagi-san",
        doraemon: "Doraemon",
        squid_game: "SQUID GAME",
        la_casa_de_papel: "La Casa de Papel",
        strangers_from_hell: "Strangers from Hell",
        la_casa_de_papel_corea: "Money Heist: Korea - Joint Economic Area",
        the_uncanny_counter: "The Uncanny Counter",
        oh_my_ghost: "Oh My Ghost",
        kono_subarashii_sekai_ni_shukufuku_o: "Konosuba: God's Blessing on This Wonderful World!",
        senpai_ga_uzai_kouhai_no_hanashi: "My Senpai is Annoying",
        boku_dake_ga_inai_machi: "Erased",
        yaku_neba: "The Promised Neverland",
        violet_evergarden: "Violet Evergarden",
        the_silent_sea: "The Silent Sea",
        violet_evergarden_movie: "Violet Evergarden: The Movie",
        love_death_plus_robots: "LOVE DEATH + ROBOTS",
        black_mirror: "Black Mirror",
        busted: "Busted!",
        watch_history: "История просмотра",
        cyberpunk_edgerunners: "Cyberpunk: Edgerunners",
        psycho_pass: "PSYCHO-PASS",
        summer_time_render: "Summer Time Rendering",
        aiuta: "Sing a Bit of Harmony",
        game_platform_account: "Аккаунты игровых платформ",
        donation_account: "Счета для пожертвований",
        height: "высота",
        height_answer: "170cm",
        weight: "масса",
        weight_answer: "60kg",
        stray: "Stray",
        journey: "Journey",
        biohazard_2: "Resident Evil 2",
        half_life: "Half-Life",
        animal_crossing_new_horizons: "Animal Crossing: New Horizons",
        the_legend_of_zelda_breath_of_the_wild: "The Legend of Zelda: Breath of the Wild",
        biohazard_village: "Resident Evil Village",
        little_nightmares: "Little Nightmares",
        vrchat: "VRChat",
        overwatch: "Overwatch",
        favorite_anime_the_movie: "Любимый анимационный фильм",
        community_account: "Аккаунты сообщества",
    },
    zh: {
        lang: "语言",
        titlename: "兴馥",
        info: "信息",
        korean_name: "韩国名字",
        sex: "性别",
        sex_answer: "男人",
        birth: "出生年份",
        birth_answer: "2003",
        birthday: "出生日期",
        birthday_answer: "2003年6月24日",
        english_name: "英文名",
        country: "国籍",
        country_answer: "大韩民国",
        live: "居住地",
        live_answer: "仁川",
        favorite_lang: "最喜欢的语言",
        japanese_name: "日本名字",
        blood: "血型",
        hobby: "爱好",
        hobby_answer: "收集收藏品",
        like: "我喜欢什么",
        like_answer: "游戏、动漫",
        chinese_name: "中文名",
        color: "最喜欢的颜色",
        mbti: "MBTI",
        dislike: "不喜欢",
        dislike_answer: "昆虫",
        email: "电子邮件",
        social_account: "社交账户",
        game_account: "游戏账号",
        copy: "复制",
        move: "链接",
        copytoclip: "复制到剪贴板",
        copied: "复制。",
        guideline: "*如果有任何恶意行为或企图，包括任何违反各项服务协议的行为，例如无故滥用朋友的请求或造成帐号使用困难等，均属非故意。即使您决定，您也可以继续处理。通过请求每个政府机构或同等组织进行调查。",
        favorite_game: "最喜欢的游戏",
        favorite_movie: "最喜欢的电影",
        favorite_anime: "最喜欢的动漫",
        favorite_drama: "最喜欢的戏剧",
        grand_theft_auto_5: "Grand Theft Auto V",
        cyberpunk_2077: "Cyberpunk 2077",
        fortnite: "Fortnite",
        detroit_become_human: "Detroit: Become Human",
        inside: "INSIDE",
        biohazard_7_resident_evil: "Resident Evil 7 Biohazard",
        portal_2: "Portal 2",
        minecraft: "Minecraft",
        the_last_of_us_remastered: "The Last of Us Remastered",
        super_mario_maker_2: "Super Mario Maker 2",
        pokemon_heartgold: "Pokémon HeartGold",
        tenki_no_ko: "Weathering With You",
        parasite: "Parasite",
        kimetsu_no_yaiba_movie_mugen_ressha_hen: "Demon Slayer -Kimetsu no Yaiba- the Movie: Mugen Train Arc",
        kimi_no_suizou_o_tabetai: "I Want to Eat Your Pancreas",
        the_avengers: "The Avengers",
        sen_to_chihiro_no_kamikakushi: "Spirited Away",
        kimi_no_na_wa: "Your Name.",
        gravity: "Gravity",
        frozen_2: "Frozen II",
        the_island: "The Island",
        in_time: "In Time",
        meitantei_conan: "Detective Conan",
        kimetsu_no_yaiba: "Demon Slayer: Kimetsu no Yaiba",
        the_idolmaster: "THE iDOLM@STER",
        kakegurui: "Kakegurui",
        crayon_shin_chan: "Crayon Shin-chan",
        spy_x_family: "SPY × FAMILY",
        karakai_jouzu_no_takagi_san: "Teasing Master Takagi-san",
        doraemon: "Doraemon",
        squid_game: "SQUID GAME",
        la_casa_de_papel: "La Casa de Papel",
        strangers_from_hell: "Strangers from Hell",
        la_casa_de_papel_corea: "Money Heist: Korea - Joint Economic Area",
        the_uncanny_counter: "The Uncanny Counter",
        oh_my_ghost: "Oh My Ghost",
        kono_subarashii_sekai_ni_shukufuku_o: "Konosuba: God's Blessing on This Wonderful World!",
        senpai_ga_uzai_kouhai_no_hanashi: "My Senpai is Annoying",
        boku_dake_ga_inai_machi: "Erased",
        yaku_neba: "The Promised Neverland",
        violet_evergarden: "Violet Evergarden",
        the_silent_sea: "The Silent Sea",
        violet_evergarden_movie: "Violet Evergarden: The Movie",
        love_death_plus_robots: "LOVE DEATH + ROBOTS",
        black_mirror: "Black Mirror",
        busted: "Busted!",
        watch_history: "观看历史",
        cyberpunk_edgerunners: "Cyberpunk: Edgerunners",
        psycho_pass: "PSYCHO-PASS",
        summer_time_render: "Summer Time Rendering",
        aiuta: "Sing a Bit of Harmony",
        game_platform_account: "游戏平台账号",
        donation_account: "捐赠账户",
        height: "高度",
        height_answer: "170cm",
        weight: "重量",
        weight_answer: "60kg",
        stray: "Stray",
        journey: "Journey",
        biohazard_2: "Resident Evil 2",
        half_life: "Half-Life",
        animal_crossing_new_horizons: "Animal Crossing: New Horizons",
        the_legend_of_zelda_breath_of_the_wild: "The Legend of Zelda: Breath of the Wild",
        biohazard_village: "Resident Evil Village",
        little_nightmares: "Little Nightmares",
        vrchat: "VRChat",
        overwatch: "Overwatch",
        favorite_anime_the_movie: "最喜欢的剧场版动漫",
        community_account: "社区账户",
    },
    zhtw: {
        lang: "語言",
        titlename: "興馥",
        info: "信息",
        korean_name: "韓國名字",
        sex: "性別",
        sex_answer: "男人",
        birth: "出生年份",
        birth_answer: "2003",
        birthday: "出生日期",
        birthday_answer: "2003年6月24日",
        english_name: "英文名",
        country: "國籍",
        country_answer: "大韓民國",
        live: "居住地",
        live_answer: "仁川",
        favorite_lang: "最喜歡的語言",
        japanese_name: "日本名字",
        blood: "血型",
        hobby: "愛好",
        hobby_answer: "收集收藏品",
        like: "我喜歡什麼",
        like_answer: "遊戲、動漫",
        chinese_name: "中文名",
        color: "最喜歡的顏色",
        mbti: "MBTI",
        dislike: "不喜歡",
        dislike_answer: "昆蟲",
        email: "電子郵件",
        social_account: "社交賬戶",
        game_account: "遊戲賬號",
        copy: "複製",
        move: "鏈接",
        copytoclip: "複製到剪貼板",
        copied: "複製。",
        guideline: "*如果有任何惡意行為或企圖，包括任何違反各項服務協議的行為，例如無故濫用朋友的請求或造成帳號使用困難的行為，均屬非故意。即使您決定，您也可以繼續處理通過請求每個政府機構或同等組織進行調查。",
        favorite_game: "最喜歡的遊戲",
        favorite_movie: "最喜歡的電影",
        favorite_anime: "最喜歡的動漫",
        favorite_drama: "最喜歡的戲劇",
        grand_theft_auto_5: "Grand Theft Auto V",
        cyberpunk_2077: "Cyberpunk 2077",
        fortnite: "Fortnite",
        detroit_become_human: "Detroit: Become Human",
        inside: "INSIDE",
        biohazard_7_resident_evil: "Resident Evil 7 Biohazard",
        portal_2: "Portal 2",
        minecraft: "Minecraft",
        the_last_of_us_remastered: "The Last of Us Remastered",
        super_mario_maker_2: "Super Mario Maker 2",
        pokemon_heartgold: "Pokémon HeartGold",
        tenki_no_ko: "Weathering With You",
        parasite: "Parasite",
        kimetsu_no_yaiba_movie_mugen_ressha_hen: "Demon Slayer -Kimetsu no Yaiba- the Movie: Mugen Train Arc",
        kimi_no_suizou_o_tabetai: "I Want to Eat Your Pancreas",
        the_avengers: "The Avengers",
        sen_to_chihiro_no_kamikakushi: "Spirited Away",
        kimi_no_na_wa: "Your Name.",
        gravity: "Gravity",
        frozen_2: "Frozen II",
        the_island: "The Island",
        in_time: "In Time",
        meitantei_conan: "Detective Conan",
        kimetsu_no_yaiba: "Demon Slayer: Kimetsu no Yaiba",
        the_idolmaster: "THE iDOLM@STER",
        kakegurui: "Kakegurui",
        crayon_shin_chan: "Crayon Shin-chan",
        spy_x_family: "SPY × FAMILY",
        karakai_jouzu_no_takagi_san: "Teasing Master Takagi-san",
        doraemon: "Doraemon",
        squid_game: "SQUID GAME",
        la_casa_de_papel: "La Casa de Papel",
        strangers_from_hell: "Strangers from Hell",
        la_casa_de_papel_corea: "Money Heist: Korea - Joint Economic Area",
        the_uncanny_counter: "The Uncanny Counter",
        oh_my_ghost: "Oh My Ghost",
        kono_subarashii_sekai_ni_shukufuku_o: "Konosuba: God's Blessing on This Wonderful World!",
        senpai_ga_uzai_kouhai_no_hanashi: "My Senpai is Annoying",
        boku_dake_ga_inai_machi: "Erased",
        yaku_neba: "The Promised Neverland",
        violet_evergarden: "Violet Evergarden",
        the_silent_sea: "The Silent Sea",
        violet_evergarden_movie: "Violet Evergarden: The Movie",
        love_death_plus_robots: "LOVE DEATH + ROBOTS",
        black_mirror: "Black Mirror",
        busted: "Busted!",
        watch_history: "觀看歷史",
        cyberpunk_edgerunners: "Cyberpunk: Edgerunners",
        psycho_pass: "PSYCHO-PASS",
        summer_time_render: "Summer Time Rendering",
        aiuta: "Sing a Bit of Harmony",
        game_platform_account: "遊戲平台賬號",
        donation_account: "捐贈賬戶",
        height: "高度",
        height_answer: "170cm",
        weight: "重量",
        weight_answer: "60kg",
        stray: "Stray",
        journey: "Journey",
        biohazard_2: "Resident Evil 2",
        half_life: "Half-Life",
        animal_crossing_new_horizons: "Animal Crossing: New Horizons",
        the_legend_of_zelda_breath_of_the_wild: "The Legend of Zelda: Breath of the Wild",
        biohazard_village: "Resident Evil Village",
        little_nightmares: "Little Nightmares",
        vrchat: "VRChat",
        overwatch: "Overwatch",
        favorite_anime_the_movie: "最喜歡的劇場版動漫",
        community_account: "社區賬戶",
    },
    ja: {
        lang: "言語",
        titlename: "フンボク",
        info: "情報",
        korean_name: "韓国の名前",
        sex: "性別",
        sex_answer: "男",
        birth: "出生年度",
        birth_answer: "2003年",
        birthday: "生年月日",
        birthday_answer: "2003年6月24日",
        english_name: "英語名",
        country: "国籍",
        country_answer: "大韓民国",
        live: "居住地",
        live_answer: "仁川",
        favorite_lang: "好きな言語",
        japanese_name: "日本の名前",
        blood: "血液型",
        hobby: "趣味",
        hobby_answer: "収集品集め",
        like: "好きなこと",
        like_answer: "ゲーム、アニメ",
        chinese_name: "漢字の名前",
        color: "好きな色",
        mbti: "MBTI",
        dislike: "嫌いなもの",
        dislike_answer: "虫",
        email: "Eメール",
        social_account: "ソーシャルアカウント",
        game_account: "ゲームアカウント",
        copy: "コピー",
        move: "リンク",
        copytoclip: "クリップボードにコピー",
        copied: "コピーされました。",
        guideline: "*明確な理由なしに友人の要請を乱発したり、アカウント利用に困難をきたすよう誘導するなど、各サービス約款に反する行為を含め、すべての悪意的な行為や試みがある場合、故意性がないと判断しても各政府機関またはそれに準ずる団体に要請して捜査を進めることができます。",
        favorite_game: "好きなゲーム",
        favorite_movie: "好きな映画",
        favorite_anime: "好きなアニメ",
        favorite_drama: "好きなドラマ",
        grand_theft_auto_5: "グランド・セフト・オートV",
        cyberpunk_2077: "サイバーパンク2077",
        fortnite: "フォートナイト",
        detroit_become_human: "デトロイト ビカム ヒューマン",
        inside: "インサイド",
        biohazard_7_resident_evil: "バイオハザード 7 レジデント イービル",
        portal_2: "ポータル2",
        minecraft: "マインクラフト",
        the_last_of_us_remastered: "ザ・ラスト・オブ・アス リマスタード",
        super_mario_maker_2: "スーパーマリオメーカー2",
        pokemon_heartgold: "ポケットモンスター ハートゴールド",
        tenki_no_ko: "天気の子",
        parasite: "パラサイト 半地下の家族",
        kimetsu_no_yaiba_movie_mugen_ressha_hen: "劇場版「鬼滅の刃」無限列車編",
        kimi_no_suizou_o_tabetai: "君の膵臓をたべたい",
        the_avengers: "アベンジャーズ",
        sen_to_chihiro_no_kamikakushi: "千と千尋の神隠し",
        kimi_no_na_wa: "君の名は。",
        gravity: "ゼロ・グラビティ",
        frozen_2: "アナと雪の女王2",
        the_island: "アイランド",
        in_time: "TIME/タイム",
        meitantei_conan: "名探偵コナン",
        kimetsu_no_yaiba: "鬼滅の刃",
        the_idolmaster: "アイドルマスター",
        kakegurui: "賭󠄀ケグルイ",
        crayon_shin_chan: "クレヨンしんちゃん",
        spy_x_family: "スパイファミリー",
        karakai_jouzu_no_takagi_san: "からかい上手の高木さん",
        doraemon: "ドラえもん",
        squid_game: "イカゲーム",
        la_casa_de_papel: "ペーパー・ハウス",
        strangers_from_hell: "他人は地獄だ",
        la_casa_de_papel_corea: "ペーパー・ハウス・コリア: 統一通貨を奪え",
        the_uncanny_counter: "悪霊狩猟団: カウンターズ",
        oh_my_ghost: "ああ、私の幽霊さま",
        kono_subarashii_sekai_ni_shukufuku_o: "この素晴らしい世界に祝福を!",
        senpai_ga_uzai_kouhai_no_hanashi: "先輩がうざい後輩の話",
        boku_dake_ga_inai_machi: "僕だけがいない街",
        yaku_neba: "約束のネバーランド",
        violet_evergarden: "ヴァイオレット・エヴァーガーデン",
        the_silent_sea: "静かなる海",
        violet_evergarden_movie: "劇場版 ヴァイオレット・エヴァーガーデン",
        love_death_plus_robots: "ラブ、デス&ロボット",
        black_mirror: "ブラック・ミラー",
        busted: "犯人はお前だ!",
        watch_history: "視聴記録",
        cyberpunk_edgerunners: "サイバーパンク エッジランナーズ",
        psycho_pass: "PSYCHO-PASS サイコパス",
        summer_time_render: "サマータイムレンダ",
        aiuta: "アイの歌声を聴かせて",
        game_platform_account: "ゲームプラットフォームのアカウント",
        donation_account: "寄付口座",
        height: "身長",
        height_answer: "170cm",
        weight: "重量",
        weight_answer: "60kg",
        stray: "ストレイ",
        journey: "風ノ旅ビト",
        biohazard_2: "バイオハザード RE:2",
        half_life: "ハーフライフ",
        animal_crossing_new_horizons: "あつまれ どうぶつの森",
        the_legend_of_zelda_breath_of_the_wild: "ゼルダの伝説 ブレス オブ ザ ワイルド",
        biohazard_village: "バイオハザード ヴィレッジ",
        little_nightmares: "リトルナイトメア",
        vrchat: "VRチャット",
        overwatch: "オーバーウォッチ",
        favorite_anime_the_movie: "好きな劇場版アニメ",
        community_account: "コミュニティ アカウント",
    },
    ko: {
        lang: "언어",
        titlename: "흥복",
        info: "정보",
        korean_name: "한국 이름",
        sex: "성별",
        sex_answer: "남",
        birth: "출생년도",
        birth_answer: "2003년",
        birthday: "생년월일",
        birthday_answer: "2003년 6월 24일",
        english_name: "영어 이름",
        country: "국적",
        country_answer: "대한민국",
        live: "거주지",
        live_answer: "인천",
        favorite_lang: "좋아하는 언어",
        japanese_name: "일본 이름",
        blood: "혈액형",
        hobby: "취미",
        hobby_answer: "수집품 모으기",
        like: "좋아하는 것",
        like_answer: "게임, 애니메이션",
        chinese_name: "한자 이름",
        color: "좋아하는 색",
        mbti: "MBTI",
        dislike: "싫어하는 것",
        dislike_answer: "벌레",
        email: "이메일",
        social_account: "소셜 계정",
        game_account: "게임 계정",
        copy: "복사",
        move: "이동",
        copytoclip: "클립보드에 복사",
        copied: "복사 되었습니다.",
        guideline: "*명확한 사유 없이 친구 요청을 남발하거나, 계정 이용에 어려움을 겪도록 유도하는 등, 각 서비스 약관의 위배되는 행위를 포함하여 모든 악의적인 행위나 시도가 있을경우 고의성이 없다고 판단할지라도 각 정부 기관 혹은 그에 준하는 단체에 요청하여 수사를 진행할 수 있습니다.",
        favorite_game: "좋아하는 게임",
        favorite_movie: "좋아하는 영화",
        favorite_anime: "좋아하는 애니메이션",
        favorite_drama: "좋아하는 드라마",
        grand_theft_auto_5: "그랜드 테프트 오토 V",
        cyberpunk_2077: "사이버펑크 2077",
        fortnite: "포트나이트",
        detroit_become_human: "디트로이트: 비컴 휴먼",
        inside: "인사이드",
        biohazard_7_resident_evil: "바이오하자드 7 레이전트 이블",
        portal_2: "포탈 2",
        minecraft: "마인크래프트",
        the_last_of_us_remastered: "더 라스트 오브 어스 리마스터드",
        super_mario_maker_2: "슈퍼 마리오 메이커 2",
        pokemon_heartgold: "포켓몬스터 하트골드",
        tenki_no_ko: "날씨의 아이",
        parasite: "기생충",
        kimetsu_no_yaiba_movie_mugen_ressha_hen: "극장판 귀멸의 칼날: 무한열차편",
        kimi_no_suizou_o_tabetai: "너의 췌장을 먹고 싶어",
        the_avengers: "어벤져스",
        sen_to_chihiro_no_kamikakushi: "센과 치히로의 행방불명",
        kimi_no_na_wa: "너의 이름은.",
        gravity: "그래비티",
        frozen_2: "겨울왕국 2",
        the_island: "아일랜드",
        in_time: "인 타임",
        meitantei_conan: "명탐정 코난",
        kimetsu_no_yaiba: "귀멸의 칼날",
        the_idolmaster: "아이돌 마스터",
        kakegurui: "카케구루이",
        crayon_shin_chan: "짱구는 못말려",
        spy_x_family: "스파이 패밀리",
        karakai_jouzu_no_takagi_san: "장난을 잘 치는 타카기 양",
        doraemon: "도라에몽",
        squid_game: "오징어 게임",
        la_casa_de_papel: "종이의 집",
        strangers_from_hell: "타인은 지옥이다",
        la_casa_de_papel_corea: "종이의 집: 공동경제구역",
        the_uncanny_counter: "경이로운 소문",
        oh_my_ghost: "오 나의 귀신님",
        kono_subarashii_sekai_ni_shukufuku_o: "이 멋진 세계에 축복을!",
        senpai_ga_uzai_kouhai_no_hanashi: "선배가 짜증나는 후배이야기",
        boku_dake_ga_inai_machi: "나만이 없는 거리",
        yaku_neba: "약속의 네버랜드",
        violet_evergarden: "바이올렛 에버가든",
        the_silent_sea: "고요의 바다",
        violet_evergarden_movie: "극장판 바이올렛 에버가든",
        love_death_plus_robots: "러브, 데스 + 로봇",
        black_mirror: "블랙 미러",
        busted: "범인은 바로 너!",
        watch_history: "시청 기록",
        cyberpunk_edgerunners: "사이버펑크: 엣지러너",
        psycho_pass: "사이코패스",
        summer_time_render: "서머타임 렌더",
        aiuta: "아이의 노랫소리를 들려줘",
        game_platform_account: "게임 플랫폼 계정",
        donation_account: "후원 계정",
        height: "신장",
        height_answer: "170cm",
        weight: "무게",
        weight_answer: "60kg",
        stray: "스트레이",
        journey: "저니",
        biohazard_2: "바이오하자드 RE:2",
        half_life: "하프라이프",
        animal_crossing_new_horizons: "모여봐요 동물의 숲",
        the_legend_of_zelda_breath_of_the_wild: "젤다의 전설 브레스 오브 더 와일드",
        biohazard_village: "바이오하자드 빌리지",
        little_nightmares: "리틀 나이트메어",
        vrchat: "VR챗",
        overwatch: "오버워치",
        favorite_anime_the_movie: "좋아하는 극장판 애니메이션",
        community_account: "커뮤니티 계정",
    },
}

function getLanguage() {
    return navigator.language || navigator.userLanguage;
}

function init(localeStr) {
    document.getElementById("locale").textContent = localeStr
}

const currentLang = getLanguage()
init(currentLang)
render(currentLang.substr(0, 2))

function render(locale) {
    const $lang = document.querySelectorAll("[data-lang]")
    $lang.forEach(el => {
        const code = el.dataset.lang
        el.textContent = lang[locale][code]
    })
}

document.getElementById("btn-en").addEventListener("click", e => {
    render("en")
})

document.getElementById("btn-ko").addEventListener("click", e => {
    render("ko")
})

document.getElementById("btn-ja").addEventListener("click", e => {
    render("ja")
})

document.getElementById("btn-de").addEventListener("click", e => {
    render("de")
})

document.getElementById("btn-es").addEventListener("click", e => {
    render("es")
})

document.getElementById("btn-fr").addEventListener("click", e => {
    render("fr")
})

document.getElementById("btn-it").addEventListener("click", e => {
    render("it")
})

document.getElementById("btn-pt").addEventListener("click", e => {
    render("pt")
})

document.getElementById("btn-ru").addEventListener("click", e => {
    render("ru")
})

document.getElementById("btn-zh").addEventListener("click", e => {
    render("zh")
})

document.getElementById("btn-zh-TW").addEventListener("click", e => {
    render("zhtw")
})