
const lang = {
    en: {
        lang: "Language",
        titlename: "HungBok",
        info: "Information",
        korean_name: "Korean Name",
        sex: "Gender",
        sex_answer: "Man",
        birth: "Year of Birth",
        birth_answer: "2003",
        birthday: "Date of Birth",
        birthday_answer: "June 24, 2003",
        english_name: "English Name",
        country: "Nationality",
        country_answer: "Republic of Korea",
        live: "Residence",
        live_answer: "Incheon",
        favorite_lang: "Favorite Language",
        japanese_name: "Japanese Name",
        blood: "Blood Type",
        hobby: "Hobby",
        hobby_answer: "to collect",
        like: "Like",
        like_answer: "Game, Anime",
        chinese_name: "Chinese Name",
        color: "Favorite Color",
        mbti: "MBTI",
        dislike: "Dislike",
        dislike_answer: "Insect",
        email: "E-mail",
        social_account: "Social Accounts",
        game_account: "Game Accounts",
        copy: "Copy",
        move: "Link",
        copytoclip: "Copy to Clipboard",
        copied: "Copied.",
        guideline: "*In the event of any malicious acts or attempts, including acts that violate the terms of service, such as excessive friend requests without clear reasons or inducing difficulties in using an account, each government agency or You can proceed with the investigation by requesting a similar organization.",
        favorite_game: "Favorite Games",
        favorite_movie: "Favorite Movies",
        favorite_anime: "Favorite Animations",
        favorite_drama: "Favorite TV Series",
        grand_theft_auto_5: "Grand Theft Auto V",
        cyberpunk_2077: "Cyberpunk 2077",
        fortnite: "Fortnite",
        detroit_become_human: "Detroit: Become Human",
        inside: "INSIDE",
        biohazard_7_resident_evil: "Resident Evil 7 Biohazard",
        portal_2: "Portal 2",
        minecraft: "Minecraft",
        the_last_of_us_remastered: "The Last of Us Remastered",
        super_mario_maker_2: "Super Mario Maker 2",
        pokemon_heartgold: "Pokémon HeartGold",
        tenki_no_ko: "Weathering With You",
        parasite: "Parasite",
        kimetsu_no_yaiba_movie_mugen_ressha_hen: "Demon Slayer -Kimetsu no Yaiba- the Movie: Mugen Train Arc",
        kimi_no_suizou_o_tabetai: "I Want to Eat Your Pancreas",
        the_avengers: "The Avengers",
        sen_to_chihiro_no_kamikakushi: "Spirited Away",
        kimi_no_na_wa: "Your Name.",
        gravity: "Gravity",
        frozen_2: "Frozen II",
        the_island: "The Island",
        in_time: "In Time",
        meitantei_conan: "Case Closed",
        kimetsu_no_yaiba: "Demon Slayer: Kimetsu no Yaiba",
        the_idolmaster: "THE iDOLM@STER",
        kakegurui: "Kakegurui",
        crayon_shin_chan: "Crayon Shin-chan",
        spy_x_family: "SPY × FAMILY",
        karakai_jouzu_no_takagi_san: "Teasing Master Takagi-san",
        doraemon: "Doraemon",
        squid_game: "SQUID GAME",
        la_casa_de_papel: "La Casa de Papel",
        strangers_from_hell: "Strangers from Hell",
        la_casa_de_papel_corea: "Money Heist: Korea - Joint Economic Area",
        the_uncanny_counter: "The Uncanny Counter",
        oh_my_ghost: "Oh My Ghost",
        kono_subarashii_sekai_ni_shukufuku_o: "Konosuba: God's Blessing on This Wonderful World!",
        senpai_ga_uzai_kouhai_no_hanashi: "My Senpai is Annoying",
        boku_dake_ga_inai_machi: "Erased",
        yaku_neba: "The Promised Neverland",
        violet_evergarden: "Violet Evergarden",
        the_silent_sea: "The Silent Sea",
        violet_evergarden_movie: "Violet Evergarden: The Movie",
        love_death_plus_robots: "LOVE DEATH + ROBOTS",
        black_mirror: "Black Mirror",
        busted: "Busted!",
        watch_history: "Watch History",
        cyberpunk_edgerunners: "Cyberpunk: Edgerunners",
        psycho_pass: "PSYCHO-PASS",
        summer_time_render: "Summer Time Rendering",
        aiuta: "Sing a Bit of Harmony",
        game_platform_account: "Game Platform Accounts",
        donation_account: "Donation Accounts",
        height: "Height",
        height_answer: "5'6''",
        weight: "Weight",
        weight_answer: "132lb",
        stray: "Stray",
        journey: "Journey",
        biohazard_2: "Resident Evil 2",
        half_life: "Half-Life",
        animal_crossing_new_horizons: "Animal Crossing: New Horizons",
        the_legend_of_zelda_breath_of_the_wild: "The Legend of Zelda: Breath of the Wild",
        biohazard_village: "Resident Evil Village",
        little_nightmares: "Little Nightmares",
        vrchat: "VRChat",
        overwatch: "Overwatch",
        favorite_anime_the_movie: "Favorite Animation The Movies",
        community_account: "Community Accounts",
    },
    ja: {
        lang: "言語",
        titlename: "フンボク",
        info: "情報",
        korean_name: "韓国の名前",
        sex: "性別",
        sex_answer: "男",
        birth: "出生年度",
        birth_answer: "2003年",
        birthday: "生年月日",
        birthday_answer: "2003年6月24日",
        english_name: "英語名",
        country: "国籍",
        country_answer: "大韓民国",
        live: "居住地",
        live_answer: "仁川",
        favorite_lang: "好きな言語",
        japanese_name: "日本の名前",
        blood: "血液型",
        hobby: "趣味",
        hobby_answer: "収集品集め",
        like: "好きなこと",
        like_answer: "ゲーム、アニメ",
        chinese_name: "漢字の名前",
        color: "好きな色",
        mbti: "MBTI",
        dislike: "嫌いなもの",
        dislike_answer: "虫",
        email: "Eメール",
        social_account: "ソーシャルアカウント",
        game_account: "ゲームアカウント",
        copy: "コピー",
        move: "リンク",
        copytoclip: "クリップボードにコピー",
        copied: "コピーされました。",
        guideline: "*明確な理由なしに友人の要請を乱発したり、アカウント利用に困難をきたすよう誘導するなど、各サービス約款に反する行為を含め、すべての悪意的な行為や試みがある場合、故意性がないと判断しても各政府機関またはそれに準ずる団体に要請して捜査を進めることができます。",
        favorite_game: "好きなゲーム",
        favorite_movie: "好きな映画",
        favorite_anime: "好きなアニメ",
        favorite_drama: "好きなドラマ",
        grand_theft_auto_5: "グランド・セフト・オートV",
        cyberpunk_2077: "サイバーパンク2077",
        fortnite: "フォートナイト",
        detroit_become_human: "デトロイト ビカム ヒューマン",
        inside: "インサイド",
        biohazard_7_resident_evil: "バイオハザード 7 レジデント イービル",
        portal_2: "ポータル2",
        minecraft: "マインクラフト",
        the_last_of_us_remastered: "ザ・ラスト・オブ・アス リマスタード",
        super_mario_maker_2: "スーパーマリオメーカー2",
        pokemon_heartgold: "ポケットモンスター ハートゴールド",
        tenki_no_ko: "天気の子",
        parasite: "パラサイト 半地下の家族",
        kimetsu_no_yaiba_movie_mugen_ressha_hen: "劇場版「鬼滅の刃」無限列車編",
        kimi_no_suizou_o_tabetai: "君の膵臓をたべたい",
        the_avengers: "アベンジャーズ",
        sen_to_chihiro_no_kamikakushi: "千と千尋の神隠し",
        kimi_no_na_wa: "君の名は。",
        gravity: "ゼロ・グラビティ",
        frozen_2: "アナと雪の女王2",
        the_island: "アイランド",
        in_time: "TIME/タイム",
        meitantei_conan: "名探偵コナン",
        kimetsu_no_yaiba: "鬼滅の刃",
        the_idolmaster: "アイドルマスター",
        kakegurui: "賭󠄀ケグルイ",
        crayon_shin_chan: "クレヨンしんちゃん",
        spy_x_family: "スパイファミリー",
        karakai_jouzu_no_takagi_san: "からかい上手の高木さん",
        doraemon: "ドラえもん",
        squid_game: "イカゲーム",
        la_casa_de_papel: "ペーパー・ハウス",
        strangers_from_hell: "他人は地獄だ",
        la_casa_de_papel_corea: "ペーパー・ハウス・コリア: 統一通貨を奪え",
        the_uncanny_counter: "悪霊狩猟団: カウンターズ",
        oh_my_ghost: "ああ、私の幽霊さま",
        kono_subarashii_sekai_ni_shukufuku_o: "この素晴らしい世界に祝福を!",
        senpai_ga_uzai_kouhai_no_hanashi: "先輩がうざい後輩の話",
        boku_dake_ga_inai_machi: "僕だけがいない街",
        yaku_neba: "約束のネバーランド",
        violet_evergarden: "ヴァイオレット・エヴァーガーデン",
        the_silent_sea: "静かなる海",
        violet_evergarden_movie: "劇場版 ヴァイオレット・エヴァーガーデン",
        love_death_plus_robots: "ラブ、デス&ロボット",
        black_mirror: "ブラック・ミラー",
        busted: "犯人はお前だ!",
        watch_history: "視聴記録",
        cyberpunk_edgerunners: "サイバーパンク エッジランナーズ",
        psycho_pass: "PSYCHO-PASS サイコパス",
        summer_time_render: "サマータイムレンダ",
        aiuta: "アイの歌声を聴かせて",
        game_platform_account: "ゲームプラットフォームのアカウント",
        donation_account: "寄付口座",
        height: "身長",
        height_answer: "170cm",
        weight: "重量",
        weight_answer: "60kg",
        stray: "ストレイ",
        journey: "風ノ旅ビト",
        biohazard_2: "バイオハザード RE:2",
        half_life: "ハーフライフ",
        animal_crossing_new_horizons: "あつまれ どうぶつの森",
        the_legend_of_zelda_breath_of_the_wild: "ゼルダの伝説 ブレス オブ ザ ワイルド",
        biohazard_village: "バイオハザード ヴィレッジ",
        little_nightmares: "リトルナイトメア",
        vrchat: "VRチャット",
        overwatch: "オーバーウォッチ",
        favorite_anime_the_movie: "好きな劇場版アニメ",
        community_account: "コミュニティ アカウント",
    },
    ko: {
        lang: "언어",
        titlename: "흥복",
        info: "정보",
        korean_name: "한국 이름",
        sex: "성별",
        sex_answer: "남",
        birth: "출생년도",
        birth_answer: "2003년",
        birthday: "생년월일",
        birthday_answer: "2003년 6월 24일",
        english_name: "영어 이름",
        country: "국적",
        country_answer: "대한민국",
        live: "거주지",
        live_answer: "인천",
        favorite_lang: "좋아하는 언어",
        japanese_name: "일본 이름",
        blood: "혈액형",
        hobby: "취미",
        hobby_answer: "수집품 모으기",
        like: "좋아하는 것",
        like_answer: "게임, 애니메이션",
        chinese_name: "한자 이름",
        color: "좋아하는 색",
        mbti: "MBTI",
        dislike: "싫어하는 것",
        dislike_answer: "벌레",
        email: "이메일",
        social_account: "소셜 계정",
        game_account: "게임 계정",
        copy: "복사",
        move: "이동",
        copytoclip: "클립보드에 복사",
        copied: "복사 되었습니다.",
        guideline: "*명확한 사유 없이 친구 요청을 남발하거나, 계정 이용에 어려움을 겪도록 유도하는 등, 각 서비스 약관의 위배되는 행위를 포함하여 모든 악의적인 행위나 시도가 있을경우 고의성이 없다고 판단할지라도 각 정부 기관 혹은 그에 준하는 단체에 요청하여 수사를 진행할 수 있습니다.",
        favorite_game: "좋아하는 게임",
        favorite_movie: "좋아하는 영화",
        favorite_anime: "좋아하는 애니메이션",
        favorite_drama: "좋아하는 드라마",
        grand_theft_auto_5: "그랜드 테프트 오토 V",
        cyberpunk_2077: "사이버펑크 2077",
        fortnite: "포트나이트",
        detroit_become_human: "디트로이트: 비컴 휴먼",
        inside: "인사이드",
        biohazard_7_resident_evil: "바이오하자드 7 레이전트 이블",
        portal_2: "포탈 2",
        minecraft: "마인크래프트",
        the_last_of_us_remastered: "더 라스트 오브 어스 리마스터드",
        super_mario_maker_2: "슈퍼 마리오 메이커 2",
        pokemon_heartgold: "포켓몬스터 하트골드",
        tenki_no_ko: "날씨의 아이",
        parasite: "기생충",
        kimetsu_no_yaiba_movie_mugen_ressha_hen: "극장판 귀멸의 칼날: 무한열차편",
        kimi_no_suizou_o_tabetai: "너의 췌장을 먹고 싶어",
        the_avengers: "어벤져스",
        sen_to_chihiro_no_kamikakushi: "센과 치히로의 행방불명",
        kimi_no_na_wa: "너의 이름은.",
        gravity: "그래비티",
        frozen_2: "겨울왕국 2",
        the_island: "아일랜드",
        in_time: "인 타임",
        meitantei_conan: "명탐정 코난",
        kimetsu_no_yaiba: "귀멸의 칼날",
        the_idolmaster: "아이돌 마스터",
        kakegurui: "카케구루이",
        crayon_shin_chan: "짱구는 못말려",
        spy_x_family: "스파이 패밀리",
        karakai_jouzu_no_takagi_san: "장난을 잘 치는 타카기 양",
        doraemon: "도라에몽",
        squid_game: "오징어 게임",
        la_casa_de_papel: "종이의 집",
        strangers_from_hell: "타인은 지옥이다",
        la_casa_de_papel_corea: "종이의 집: 공동경제구역",
        the_uncanny_counter: "경이로운 소문",
        oh_my_ghost: "오 나의 귀신님",
        kono_subarashii_sekai_ni_shukufuku_o: "이 멋진 세계에 축복을!",
        senpai_ga_uzai_kouhai_no_hanashi: "선배가 짜증나는 후배이야기",
        boku_dake_ga_inai_machi: "나만이 없는 거리",
        yaku_neba: "약속의 네버랜드",
        violet_evergarden: "바이올렛 에버가든",
        the_silent_sea: "고요의 바다",
        violet_evergarden_movie: "극장판 바이올렛 에버가든",
        love_death_plus_robots: "러브, 데스 + 로봇",
        black_mirror: "블랙 미러",
        busted: "범인은 바로 너!",
        watch_history: "시청 기록",
        cyberpunk_edgerunners: "사이버펑크: 엣지러너",
        psycho_pass: "사이코패스",
        summer_time_render: "서머타임 렌더",
        aiuta: "아이의 노랫소리를 들려줘",
        game_platform_account: "게임 플랫폼 계정",
        donation_account: "후원 계정",
        height: "신장",
        height_answer: "170cm",
        weight: "무게",
        weight_answer: "60kg",
        stray: "스트레이",
        journey: "저니",
        biohazard_2: "바이오하자드 RE:2",
        half_life: "하프라이프",
        animal_crossing_new_horizons: "모여봐요 동물의 숲",
        the_legend_of_zelda_breath_of_the_wild: "젤다의 전설 브레스 오브 더 와일드",
        biohazard_village: "바이오하자드 빌리지",
        little_nightmares: "리틀 나이트메어",
        vrchat: "VR챗",
        overwatch: "오버워치",
        favorite_anime_the_movie: "좋아하는 극장판 애니메이션",
        community_account: "커뮤니티 계정",
    },
}

function getLanguage() {
    return navigator.language || navigator.userLanguage;
}

function init(localeStr) {
    document.getElementById("locale").textContent = localeStr
}

const currentLang = getLanguage()
init(currentLang)
render(currentLang.substr(0, 2))

function render(locale) {
    const $lang = document.querySelectorAll("[data-lang]")
    $lang.forEach(el => {
        const code = el.dataset.lang
        el.textContent = lang[locale][code]
    })
}

document.getElementById("btn-en").addEventListener("click", e => {
    render("en")
})

document.getElementById("btn-ko").addEventListener("click", e => {
    render("ko")
})

document.getElementById("btn-ja").addEventListener("click", e => {
    render("ja")
})

document.getElementById("btn-de").addEventListener("click", e => {
    render("de")
})

document.getElementById("btn-es").addEventListener("click", e => {
    render("es")
})

document.getElementById("btn-fr").addEventListener("click", e => {
    render("fr")
})

document.getElementById("btn-it").addEventListener("click", e => {
    render("it")
})

document.getElementById("btn-pt").addEventListener("click", e => {
    render("pt")
})

document.getElementById("btn-ru").addEventListener("click", e => {
    render("ru")
})

document.getElementById("btn-zh").addEventListener("click", e => {
    render("zh")
})

document.getElementById("btn-zh-TW").addEventListener("click", e => {
    render("zhtw")
})